# Generated by Django 5.0.6 on 2026-06-12 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("circles", "0006_resource"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CollaborationRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "project_topic",
                    models.CharField(
                        help_text="Project or topic for collaboration", max_length=200
                    ),
                ),
                (
                    "collaboration_goal",
                    models.CharField(
                        help_text="Goal of the collaboration", max_length=300
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        help_text="Message explaining collaboration intent",
                        max_length=1000,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="pending",
                        help_text="Request status",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "circle",
                    models.ForeignKey(
                        help_text="Circle context for collaboration",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collaboration_requests",
                        to="circles.circle",
                    ),
                ),
                (
                    "receiver",
                    models.ForeignKey(
                        help_text="Peer receiving collaboration request",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mentorship_received_collaboration_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        help_text="Peer initiating collaboration",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mentorship_sent_collaboration_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Collaboration Request",
                "verbose_name_plural": "Collaboration Requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GuidanceRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        help_text="Subject area (e.g., Neural Networks)", max_length=200
                    ),
                ),
                (
                    "guidance_topic",
                    models.CharField(
                        help_text="Specific topic for guidance", max_length=300
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        help_text="Detailed message explaining what help is needed",
                        max_length=1000,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="pending",
                        help_text="Request status",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "circle",
                    models.ForeignKey(
                        help_text="Circle context for the guidance",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guidance_requests",
                        to="circles.circle",
                    ),
                ),
                (
                    "mentor",
                    models.ForeignKey(
                        help_text="Mentor being requested",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_guidance_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        help_text="Student requesting guidance",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_guidance_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Guidance Request",
                "verbose_name_plural": "Guidance Requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "conversation_type",
                    models.CharField(
                        choices=[
                            ("guidance", "Guidance (Mentor ↔ Student)"),
                            ("collaboration", "Collaboration (Peer ↔ Peer)"),
                        ],
                        db_index=True,
                        help_text="Type of conversation",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether conversation is active",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, help_text="Soft delete flag"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_message_at", models.DateTimeField(blank=True, null=True)),
                (
                    "circle",
                    models.ForeignKey(
                        help_text="Circle context",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversations",
                        to="circles.circle",
                    ),
                ),
                (
                    "collaboration_request",
                    models.OneToOneField(
                        blank=True,
                        help_text="Linked collaboration request (if collaboration type)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversation",
                        to="mentorship.collaborationrequest",
                    ),
                ),
                (
                    "participants",
                    models.ManyToManyField(
                        help_text="Conversation participants (exactly 2)",
                        related_name="conversations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "guidance_request",
                    models.OneToOneField(
                        blank=True,
                        help_text="Linked guidance request (if guidance type)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversation",
                        to="mentorship.guidancerequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "Conversation",
                "verbose_name_plural": "Conversations",
                "ordering": ["-last_message_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content",
                    models.TextField(help_text="Message content", max_length=2000),
                ),
                (
                    "is_read",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether message has been read",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, help_text="Soft delete flag"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        help_text="Parent conversation",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="mentorship.conversation",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        help_text="Message sender",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Message",
                "verbose_name_plural": "Messages",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="collaborationrequest",
            index=models.Index(
                fields=["receiver", "status", "-created_at"],
                name="mentorship__receive_b118a1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="collaborationrequest",
            index=models.Index(
                fields=["sender", "status", "-created_at"],
                name="mentorship__sender__715521_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="collaborationrequest",
            index=models.Index(
                fields=["circle", "-created_at"], name="mentorship__circle__89242c_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="collaborationrequest",
            unique_together={("sender", "receiver", "circle", "status")},
        ),
        migrations.AddIndex(
            model_name="guidancerequest",
            index=models.Index(
                fields=["mentor", "status", "-created_at"],
                name="mentorship__mentor__4c25d8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="guidancerequest",
            index=models.Index(
                fields=["sender", "status", "-created_at"],
                name="mentorship__sender__308491_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="guidancerequest",
            index=models.Index(
                fields=["circle", "-created_at"], name="mentorship__circle__ac40f6_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="guidancerequest",
            unique_together={("sender", "mentor", "circle", "status")},
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["conversation_type", "-created_at"],
                name="mentorship__convers_d52a91_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["is_active", "is_deleted"],
                name="mentorship__is_acti_c507dd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["-last_message_at"], name="mentorship__last_me_1ce2bb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["conversation", "-created_at"],
                name="mentorship__convers_a4f1f9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["sender", "-created_at"], name="mentorship__sender__547d56_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["is_deleted"], name="mentorship__is_dele_9dfcf1_idx"
            ),
        ),
    ]
