# Generated by Django 5.0.6 on 2026-06-13 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mentorship", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="guidancerequest",
            name="rejection_reason",
            field=models.TextField(
                blank=True,
                help_text="Reason provided by mentor when rejecting the request",
                max_length=500,
                null=True,
            ),
        ),
    ]
