# Generated by Django 6.0.5 on 2026-06-01 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Circle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the learning circle", max_length=150
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of circle goals and activities",
                        max_length=1000,
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        choices=[
                            ("mathematics", "Mathematics"),
                            ("physics", "Physics"),
                            ("chemistry", "Chemistry"),
                            ("biology", "Biology"),
                            ("computer_science", "Computer Science"),
                            ("engineering", "Engineering"),
                            ("data_science", "Data Science"),
                            ("robotics", "Robotics"),
                            ("astronomy", "Astronomy"),
                            ("other", "Other STEM"),
                        ],
                        help_text="STEM subject area",
                        max_length=50,
                    ),
                ),
                (
                    "skill_level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        default="beginner",
                        help_text="Required or target skill level",
                        max_length=20,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Circle location (city, online, etc.)",
                        max_length=200,
                    ),
                ),
                (
                    "preferred_language",
                    models.CharField(
                        choices=[
                            ("english", "English"),
                            ("spanish", "Spanish"),
                            ("french", "French"),
                            ("german", "German"),
                            ("chinese", "Chinese"),
                            ("other", "Other"),
                        ],
                        default="english",
                        help_text="Preferred communication language",
                        max_length=20,
                    ),
                ),
                (
                    "max_members",
                    models.PositiveIntegerField(
                        default=30, help_text="Maximum number of members allowed"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created this circle",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_circles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Members of this circle",
                        related_name="joined_circles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "mentors",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Mentors in this circle",
                        related_name="mentoring_circles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Learning Circle",
                "verbose_name_plural": "Learning Circles",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["domain", "skill_level"],
                        name="circles_cir_domain_edec42_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="circles_cir_created_ace838_idx"
                    ),
                    models.Index(
                        fields=["created_by"], name="circles_cir_created_a91594_idx"
                    ),
                ],
            },
        ),
    ]
