# Generated by Django 6.0.5 on 2026-06-01 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("circles", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="circle",
            name="is_private",
            field=models.BooleanField(
                default=False, help_text="Private circles require join request approval"
            ),
        ),
        migrations.AlterField(
            model_name="circle",
            name="domain",
            field=models.CharField(
                choices=[
                    ("mathematics", "Mathematics"),
                    ("physics", "Physics"),
                    ("chemistry", "Chemistry"),
                    ("biology", "Biology"),
                    ("computer_science", "Computer Science"),
                    ("engineering", "Engineering"),
                    ("data_science", "Data Science"),
                    ("robotics", "Robotics"),
                    ("astronomy", "Astronomy"),
                    ("other", "Other STEM"),
                ],
                db_index=True,
                help_text="STEM subject area",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="circle",
            name="location",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Circle location (city, online, etc.)",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="circle",
            name="preferred_language",
            field=models.CharField(
                choices=[
                    ("english", "English"),
                    ("spanish", "Spanish"),
                    ("french", "French"),
                    ("german", "German"),
                    ("chinese", "Chinese"),
                    ("other", "Other"),
                ],
                db_index=True,
                default="english",
                help_text="Preferred communication language",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="circle",
            name="skill_level",
            field=models.CharField(
                choices=[
                    ("beginner", "Beginner"),
                    ("intermediate", "Intermediate"),
                    ("advanced", "Advanced"),
                ],
                db_index=True,
                default="beginner",
                help_text="Required or target skill level",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="JoinRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="pending",
                        help_text="Request status: pending/accepted/rejected",
                        max_length=20,
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True,
                        help_text="Optional message from the requester",
                        max_length=500,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "circle",
                    models.ForeignKey(
                        help_text="Circle being requested to join",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="join_requests",
                        to="circles.circle",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User requesting to join",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="join_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Join Request",
                "verbose_name_plural": "Join Requests",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "circle"], name="circles_joi_user_id_67b01f_idx"
                    ),
                    models.Index(
                        fields=["status", "created_at"],
                        name="circles_joi_status_425596_idx",
                    ),
                ],
                "unique_together": {("user", "circle", "status")},
            },
        ),
    ]
