# Generated by Django 6.0.5 on 2026-06-02 11:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("circles", "0002_circle_is_private_alter_circle_domain_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="circle",
            name="archived_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the circle was archived/soft-deleted",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="circle",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Whether the circle is active/visible"
            ),
        ),
        migrations.AddField(
            model_name="circle",
            name="is_deleted",
            field=models.BooleanField(
                default=False, help_text="Whether the circle is soft-deleted"
            ),
        ),
        migrations.AddIndex(
            model_name="circle",
            index=models.Index(
                fields=["is_active", "is_deleted"],
                name="circles_cir_is_acti_3e0936_idx",
            ),
        ),
    ]
