# Generated by Django 6.0.5 on 2026-06-02 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("circles", "0003_circle_archived_at_circle_is_active_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Discussion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Discussion message content", max_length=2000
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("general", "General"),
                            ("doubts", "Doubts"),
                            ("announcements", "Announcements"),
                            ("resources", "Resources"),
                            ("projects", "Projects"),
                        ],
                        db_index=True,
                        default="general",
                        help_text="Discussion category",
                        max_length=30,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether the discussion is active",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether the discussion is soft deleted",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="When the message was sent",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When the message was last updated"
                    ),
                ),
                (
                    "circle",
                    models.ForeignKey(
                        help_text="Circle this discussion belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discussions",
                        to="circles.circle",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who sent the message",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discussions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Discussion",
                "verbose_name_plural": "Discussions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["circle", "category", "-created_at"],
                        name="circles_dis_circle__da24d6_idx",
                    ),
                    models.Index(
                        fields=["is_active", "is_deleted"],
                        name="circles_dis_is_acti_8ad751_idx",
                    ),
                ],
            },
        ),
    ]
