# Generated by Django 5.0.6 on 2026-06-07 07:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("circles", "0004_discussion"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="joinrequest",
            unique_together={("user", "circle")},
        ),
        migrations.DeleteModel(
            name="Discussion",
        ),
    ]
