# Generated by Django 5.0.6 on 2026-06-12 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("circles", "0005_alter_joinrequest_unique_together_delete_discussion"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(help_text="Resource title", max_length=255)),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of the resource",
                        max_length=1000,
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF Document"),
                            ("doc", "DOC/DOCX Document"),
                            ("ppt", "PowerPoint (PPT/PPTX)"),
                            ("link", "External Link"),
                            ("youtube", "YouTube Video"),
                            ("notes", "Notes / Text Resource"),
                        ],
                        db_index=True,
                        help_text="Type of resource",
                        max_length=20,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        help_text="Uploaded file (for PDF, DOC, PPT)",
                        null=True,
                        upload_to="circle_resources/%Y/%m/%d/",
                    ),
                ),
                (
                    "external_url",
                    models.URLField(
                        blank=True,
                        help_text="External URL (for links, YouTube)",
                        max_length=2000,
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether the resource is soft-deleted",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="When the resource was uploaded",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When the resource was last updated"
                    ),
                ),
                (
                    "circle",
                    models.ForeignKey(
                        help_text="Circle this resource belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resources",
                        to="circles.circle",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        help_text="User who uploaded the resource",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploaded_resources",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Circle Resource",
                "verbose_name_plural": "Circle Resources",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["circle", "resource_type", "-created_at"],
                        name="circles_res_circle__470b08_idx",
                    ),
                    models.Index(
                        fields=["circle", "-created_at"],
                        name="circles_res_circle__d73d58_idx",
                    ),
                    models.Index(
                        fields=["is_deleted"], name="circles_res_is_dele_b78cff_idx"
                    ),
                ],
            },
        ),
    ]
