# Generated by Django 5.0.6 on 2026-07-09 16:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("circles", "0007_alter_joinrequest_unique_together"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="joinrequest",
            unique_together={("user", "circle")},
        ),
    ]
