# Generated by Django 6.0.5 on 2026-06-01 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True, help_text="Brief bio about yourself", max_length=500
                    ),
                ),
                (
                    "profile_picture",
                    models.ImageField(blank=True, null=True, upload_to="profiles/"),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("student", "Student"),
                            ("mentor", "Mentor"),
                            ("both", "Student & Mentor"),
                        ],
                        default="student",
                        max_length=10,
                    ),
                ),
                (
                    "interests",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated STEM interests",
                        max_length=200,
                    ),
                ),
                (
                    "experience_level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        default="beginner",
                        max_length=20,
                    ),
                ),
                (
                    "skills",
                    models.TextField(blank=True, help_text="Comma-separated skills"),
                ),
                ("is_mentor", models.BooleanField(default=False)),
                (
                    "mentorship_expertise",
                    models.TextField(blank=True, help_text="Mentor expertise areas"),
                ),
                (
                    "learning_goals",
                    models.TextField(
                        blank=True, help_text="Personal learning objectives"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
                "ordering": ["-created_at"],
            },
        ),
    ]
