# Generated by Django 6.0.5 on 2026-06-01 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[("student", "Student"), ("mentor", "Mentor")],
                db_index=True,
                default="student",
                help_text="User role determines circle participation level",
                max_length=10,
            ),
        ),
    ]
