# Generated by Django 6.0.5 on 2026-06-02 08:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_userprofile_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="years_of_experience",
            field=models.IntegerField(
                blank=True,
                help_text="Years of professional experience (for mentors)",
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
