# Generated by Django 5.0.6 on 2026-06-07 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_userprofile_years_of_experience"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="availability",
            field=models.CharField(
                choices=[
                    ("available", "Available"),
                    ("busy", "Busy"),
                    ("away", "Away"),
                    ("offline", "Offline"),
                ],
                db_index=True,
                default="available",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="github",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="linkedin",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="tech_stack",
            field=models.JSONField(
                blank=True, default=list, help_text="List of tech skills/technologies"
            ),
        ),
    ]
