# Generated by Django 5.0.6 on 2026-06-12 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_remove_tech_stack_ensure_domain"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="interests",
            field=models.CharField(
                blank=True,
                help_text="Comma-separated STEM interests (multiple topics)",
                max_length=200,
            ),
        ),
    ]
