# Generated by Django 5.0.6 on 2026-06-13 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_userprofile_interests"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="profile_picture",
        ),
    ]
