# Generated by Django 5.0.6 on 2026-06-13 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("peers", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CollaborationRequest",
        ),
    ]
